// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_Api.DataBase;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(ClientDbContext))]
    [Migration("20221130100705_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Web_Api.Modules.Archiv", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("LsClientIn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LsClientOut")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeCurrency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeTransfer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Archivs");

                    b.HasData(
                        new
                        {
                            id = 1,
                            DateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LsClientIn = "2222 - 2222",
                            LsClientOut = "1111-1111",
                            TypeCurrency = "BTC",
                            TypeTransfer = "online"
                        },
                        new
                        {
                            id = 2,
                            DateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LsClientIn = "6666-6666",
                            LsClientOut = "1111-1111",
                            TypeCurrency = "ETH",
                            TypeTransfer = "online"
                        },
                        new
                        {
                            id = 3,
                            DateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LsClientIn = "5555-5555",
                            LsClientOut = "3333-3333",
                            TypeCurrency = "DOGE",
                            TypeTransfer = "online"
                        },
                        new
                        {
                            id = 4,
                            DateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LsClientIn = "2222-2222",
                            LsClientOut = "6666-6666",
                            TypeCurrency = "ETH",
                            TypeTransfer = "online"
                        },
                        new
                        {
                            id = 5,
                            DateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LsClientIn = "4444-4444",
                            LsClientOut = "2222-2222",
                            TypeCurrency = "BTC",
                            TypeTransfer = "online"
                        },
                        new
                        {
                            id = 6,
                            DateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LsClientIn = "6666-6666",
                            LsClientOut = "3333-3333",
                            TypeCurrency = "DOGE",
                            TypeTransfer = "online"
                        },
                        new
                        {
                            id = 7,
                            DateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LsClientIn = "2222-2222",
                            LsClientOut = "5555-5555",
                            TypeCurrency = "BTC",
                            TypeTransfer = "online"
                        },
                        new
                        {
                            id = 8,
                            DateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LsClientIn = "4444-4444",
                            LsClientOut = "6666-6666",
                            TypeCurrency = "ETH",
                            TypeTransfer = "online"
                        },
                        new
                        {
                            id = 9,
                            DateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LsClientIn = "6666-6666",
                            LsClientOut = "2222-2222",
                            TypeCurrency = "BTC",
                            TypeTransfer = "online"
                        },
                        new
                        {
                            id = 10,
                            DateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LsClientIn = "2222-2222",
                            LsClientOut = "6666-6666",
                            TypeCurrency = "ETH",
                            TypeTransfer = "online"
                        },
                        new
                        {
                            id = 11,
                            DateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LsClientIn = "4444-4444",
                            LsClientOut = "2222-2222",
                            TypeCurrency = "BTC",
                            TypeTransfer = "online"
                        },
                        new
                        {
                            id = 12,
                            DateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LsClientIn = "6666-6666",
                            LsClientOut = "3333-3333",
                            TypeCurrency = "DOGE",
                            TypeTransfer = "online"
                        },
                        new
                        {
                            id = 13,
                            DateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LsClientIn = "2222-2222",
                            LsClientOut = "5555-5555",
                            TypeCurrency = "BTC",
                            TypeTransfer = "online"
                        },
                        new
                        {
                            id = 14,
                            DateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LsClientIn = "4444-4444",
                            LsClientOut = "6666-6666",
                            TypeCurrency = "ETH",
                            TypeTransfer = "online"
                        },
                        new
                        {
                            id = 15,
                            DateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LsClientIn = "6666-6666",
                            LsClientOut = "2222-2222",
                            TypeCurrency = "BTC",
                            TypeTransfer = "online"
                        });
                });

            modelBuilder.Entity("Web_Api.Modules.Client", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ls")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Ls = "1111-1111",
                            Name = "Nix"
                        },
                        new
                        {
                            id = 2,
                            Ls = "3333-3333",
                            Name = "Son"
                        },
                        new
                        {
                            id = 3,
                            Ls = "4444-4444",
                            Name = "Max"
                        },
                        new
                        {
                            id = 4,
                            Ls = "5555-5555",
                            Name = "Bob"
                        },
                        new
                        {
                            id = 5,
                            Ls = "6666-6666",
                            Name = "Ana"
                        },
                        new
                        {
                            id = 6,
                            Ls = "2222-2222",
                            Name = "Tim"
                        });
                });

            modelBuilder.Entity("Web_Api.Modules.Wallet", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BTC")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DOGE")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ETH")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ls")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Wallets");

                    b.HasData(
                        new
                        {
                            id = 1,
                            BTC = 2m,
                            DOGE = 5m,
                            ETH = 0.03m,
                            Ls = "1111-1111"
                        },
                        new
                        {
                            id = 2,
                            BTC = 5m,
                            DOGE = 2m,
                            ETH = 0.3m,
                            Ls = "2222-2222"
                        },
                        new
                        {
                            id = 3,
                            BTC = 0.12m,
                            DOGE = 0.12m,
                            ETH = 2m,
                            Ls = "4444-4444"
                        },
                        new
                        {
                            id = 4,
                            BTC = 12m,
                            DOGE = 22m,
                            ETH = 1m,
                            Ls = "3333-3333"
                        },
                        new
                        {
                            id = 5,
                            BTC = 0.33m,
                            DOGE = 5m,
                            ETH = 5m,
                            Ls = "5555-5555"
                        },
                        new
                        {
                            id = 6,
                            BTC = 0.002m,
                            DOGE = 12m,
                            ETH = 12m,
                            Ls = "6666-6666"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
